[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "0.0.0"
name = "rssm-jax"
requires-python = ">=3.10,<3.12"
dependencies = [
    "jax==0.4.38",
    "equinox==0.11.11"
]

[tool.setuptools.packages.find]
include = ["rssm"]